version: '3.1'

services:

  db:
    image: mongo:4.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: exam
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8043:8043
    environment:
      DEBUG: "diamond:*"
      NODE_ENV: "dev"
      NODE_PORT: "8043"
    depends_on:
      - db